name: 123Hotels
favicon: null
layout_spectrum: 0.53657
typography_spectrum: 0.54652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004987'
    - '#ffffff'
    - '#00baf0'
    - '#a1bcd3'
    - '#326d9f'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0.19216157286427915
purpose: []
